# Generated by Django 5.2.12 on 2026-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_clean_onboarding_accesses"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunIndexing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Indexing",
                "managed": False,
            },
        ),
    ]
